language: rust

cache: cargo

rust:
  - stable

jobs:
  include:
  - env: FEATURE=test
    script:
      - cargo test
  - env: FEATURE=fmt
    install:
      - rustup component add rustfmt-preview
    script:
      - cargo fmt --all -- --check
  - env: FEATURE=clippy
    install:
      - rustup component add clippy-preview
    script:
      - cargo clippy --verbose -- -D warnings
